version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=secret
    volumes:
      - static_volume:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  static_volume:
